import * as fs from 'fs';
import * as path from 'path';
import { BlockSequence } from './gtfsTimetable';

export class HeaderGenerator {
    private outputPath: string;

    constructor(outputPath: string) {
        this.outputPath = outputPath;
    }

    public generate(blockSchedule: BlockSequence[]): void {
        let headerContent = `// Auto-generated by HeaderGenerator.ts\n`;
        headerContent += `#pragma once\n\n`;
        headerContent += `#include <cstdint>\n`;
        // Assuming CRGB and TrainRoute, TimetableEntry are defined somewhere else, otherwise might need another include.
        headerContent += `\n`;

        const classNames: string[] = [];

        for (let i = 0; i < blockSchedule.length; i++) {
            const trip = blockSchedule[i];
            const className = `Trip_${trip?.id.replace(/[^a-zA-Z0-9_]/g, '_')}`; // Sanitize to valid C++ identifier
            classNames.push(className);
            
            const colorR = trip.color ? trip.color[0] : 255;
            const colorG = trip.color ? trip.color[1] : 255;
            const colorB = trip.color ? trip.color[2] : 255;

            let startTimesStr = trip.startTimes.join(', ');
            
            let blocksStr = '';
            for (const block of trip.blocks) {
                blocksStr += `\t\t{ ${block.offsetSeconds}, ${block.blockNumber} },\n`;
            }

            headerContent += `class ${className} : public TrainRoute {\n`;
            headerContent += `  public:\n`;
            headerContent += `\tRouteSpan<TimetableEntry> getEntries() const override {\n`;
            headerContent += `\t\treturn timetable;\n`;
            headerContent += `\t}\n\n`;

            headerContent += `\tCRGB getColor() const override {\n`;
            headerContent += `\t\treturn CRGB(${colorR}, ${colorG}, ${colorB});\n`;
            headerContent += `\t}\n\n`;

            headerContent += `\tRouteSpan<uint32_t> getStartTimes() const override {\n`;
            headerContent += `\t\tstatic constexpr uint32_t startTimes[] = {\n`;
            headerContent += `\t\t\t${startTimesStr}\n`;
            headerContent += `\t\t};\n`;
            headerContent += `\t\treturn startTimes;\n`;
            headerContent += `\t}\n\n`;

            headerContent += `  private:\n`;
            headerContent += `\tstatic inline constexpr TimetableEntry timetable[] = {\n`;
            headerContent += blocksStr;
            headerContent += `\t};\n`;
            headerContent += `};\n\n\n`;
        }

        if (classNames.length > 0) {
            headerContent += classNames.map(name => `static const ${name} inst_${name};`).join('\n') + '\n\n';
        }

        headerContent += `// === Global List of Routes ===\n`;
        headerContent += `inline RouteSpan<const TrainRoute*> getAllRoutes() {\n`;
        headerContent += `\tstatic const TrainRoute* const routes[] = {\n`;
        headerContent += classNames.map(name => `\t\t&inst_${name}`).join(',\n') + '\n';
        headerContent += `\t};\n`;
        headerContent += `\treturn routes;\n`;
        headerContent += `}\n`;

        fs.writeFileSync(this.outputPath, headerContent, 'utf8');
        // console.log(`Generated header file at ${this.outputPath}`);
    }
}